manageHomework/Models/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace manageHomework.Models
{
    public class LoginViewModel
    {
        [Required(ErrorMessage = "Error.Required")]
        [EmailAddress(ErrorMessage = "Error.Email")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Error.Required")]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Display(Name = "Remember")]
        public bool RememberMe { get; set; }
    }
}

manageHomework/Models/SignUpViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace manageHomework.Models
{
    public class SignUpViewModel
    {
        [Required(ErrorMessage = "Error.Required")]
        [EmailAddress(ErrorMessage = "Error.Email")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Error.Required")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
    }
}

manageHomework/Models/UserViewModel.cs
namespace manageHomework.Models
{
    public class UserViewModel
    {
        public string Email { get; set; }
    }
}

manageHomework/Controllers/UsersController.cs
using manageHomework.Models;
using manageHomework.Services;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Formatters;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace manageHomework.Controllers
{
    public class UsersController : Controller
    {
        private readonly UserManager<IdentityUser> userManager;
        private readonly SignInManager<IdentityUser> signInManager;
        private readonly ApplicationDbContext applicationDbContext;

        public UsersController(UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager, ApplicationDbContext applicationDbContext)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
            this.applicationDbContext = applicationDbContext;
        }

        [AllowAnonymous]
        public IActionResult SignUp()
        {
            return View();
        }
        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> SignUp(SignUpViewModel request)
        {
            if(!ModelState.IsValid)
            {
                return View(request);
            }
            var user = new IdentityUser
            {
                Email = request.Email,
                UserName = request.Email
            };
            var result = await userManager.CreateAsync(user, password: request.Password);

            if (result.Succeeded)
            {
                await signInManager.SignInAsync(user, isPersistent: true);
                return RedirectToAction("Index", "Home");
            }

            foreach(var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }

            return View(request);
        }

        [AllowAnonymous]
        public IActionResult Login(string? message = null)
        {
            if(message != null)
            {
                ViewData["message"] = message;
            }

            return View();
        }
        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Login(LoginViewModel model)
        {
            if(!ModelState.IsValid)
            {
                return View(model);
            }

            var result = await signInManager.PasswordSignInAsync(model.Email, model.Password, isPersistent: true, lockoutOnFailure: false);

            if (result.Succeeded)
            {
                return RedirectToAction("Index", "Home");
            }

            ModelState.AddModelError(string.Empty, "Nombre usuario o password incorrecto");
            return View(model);
        }
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(IdentityConstants.ApplicationScheme);
            return RedirectToAction("Index", "Home");
        }
        [AllowAnonymous]
        [HttpGet]
        public ChallengeResult ExternalLogin(string provider, string returnUrl)
        {
            var urlRedirect = Url.Action("RegisterExternalUser", values: new { returnUrl });
            var externalProperties = signInManager.ConfigureExternalAuthenticationProperties(provider, urlRedirect);

            return new ChallengeResult(provider, externalProperties);
        }
        [AllowAnonymous]
        public async Task<IActionResult> RegisterExternalUser(string returnUrl, string remoteError = null)
        {
            returnUrl = string.IsNullOrEmpty(returnUrl) ? "/" : returnUrl;
            var message = "";
            if(remoteError != null)
            {
                message = $"Error remote: {remoteError}";
                return RedirectToAction("login", routeValues: new { message });

            }

            var info = await signInManager.GetExternalLoginInfoAsync();
            if(info == null)
            {
                message = "Error data external nor found!";
                return RedirectToAction("login", routeValues: new { message });
            }

            var externalResult = await signInManager.ExternalLoginSignInAsync(info.LoginProvider, info.ProviderKey, isPersistent: true, bypassTwoFactor: true);

            if (externalResult.Succeeded)
            {
                return LocalRedirect(returnUrl);
            }

            string email = "";
            if (info.Principal.HasClaim(p => p.Type == ClaimTypes.Email))
            {
                email = info.Principal.FindFirstValue(ClaimTypes.Email);
            } else
            {
                message = "Error al extraer el email de usuario externo";
                return RedirectToAction("login", routeValues: new { message });
            }

            var user = new IdentityUser { Email = email, UserName = email };

            var resultCreateUser = await userManager.CreateAsync(user);

            if (!resultCreateUser.Succeeded)
            {
                message = resultCreateUser.Errors.First().Description;
                return RedirectToAction("login", routeValues: new { message });
            }

            var resultAddLoginExternal = await userManager.AddLoginAsync(user, info);

            if(resultAddLoginExternal.Succeeded)
            {
                await signInManager.SignInAsync(user, isPersistent: true, info.LoginProvider);
                return LocalRedirect(returnUrl);
            }
            message = "Error al agregar el login";
            return RedirectToAction("login", routeValues: new { message });
        }

        [Authorize(Roles = Constants.ROLADMIN)]
        [HttpGet]
        public async Task<IActionResult> List(string? message = null)
        {
            var users = await applicationDbContext.Users.Select(u=>new UserViewModel
            {
                Email = u.Email!
            }).ToListAsync();

            var userViewModel = new UserListViewModel();
            userViewModel.Users = users;
            userViewModel.Message = message;
            return View(userViewModel);
        }
        [Authorize(Roles = Constants.ROLADMIN)]
        [HttpPost]
        public async Task<IActionResult> DoAdmin(string email)
        {
            var user = await applicationDbContext.Users.Where(u=>u.Email == email).FirstOrDefaultAsync();

            if(user == null)
            {
                return NotFound();
            }

            await userManager.AddToRoleAsync(user, Constants.ROLADMIN);


            return RedirectToAction(nameof(List), routeValues: new { message = "Rol Asignado correctamente del email " + email });
        }
        [Authorize(Roles = Constants.ROLADMIN)]
        [HttpPost]
        public async Task<IActionResult> RemoveAdmin(string email)
        {
            var user = await applicationDbContext.Users.Where(u => u.Email == email).FirstOrDefaultAsync();

            if (user == null)
            {
                return NotFound();
            }

            await userManager.RemoveFromRoleAsync(user, Constants.ROLADMIN);


            return RedirectToAction(nameof(List), routeValues: new { message = "Rol removido correctamente del email " + email });
        }
    }
}

manageHomework/Views/Users/List.cshtml
@model UserListViewModel

@{
    ViewData["Title"] = "Listado de usuarios";
    Layout = "../Shared/_Layout";
}

@if (Model.Message != null)
{
    <div class="alert alert-success" role="alert">
        @Model.Message
    </div>
}

@if (Model.Users != null)
{
    <h1>Listado de usuarios</h1>
    <form method="post">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Accion</th>
                    <th>Email</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var user in Model.Users)
                {
                    <tr>
                        <td>
                            <button class="btn btn-primary me-2" asp-action="DoAdmin" asp-route-email="@user.Email">Hacer Admin</button>
                            <button class="btn btn-danger me-2" asp-action="RemoveAdmin" asp-route-email="@user.Email">Remover Admin</button>
                        </td>
                        <td>
                            @user.Email
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </form>

}
else
{
    <p>No hay usuarios para mostrar</p>
}

manageHomework/Views/Users/Login.cshtml
@model LoginViewModel
@{
    ViewData["Title"] = "Login";
}
<h1>Login</h1>


@if (ViewData.Keys.Contains("message"))
{
    <p class="text-danger">@ViewData["message"]</p>
}

<div class="card">
    <div class="card-body">
        <form asp-action="Login">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="mb-3">
                <label asp-for="Email" class="form-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label asp-for="Password" class="form-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <input asp-for="RememberMe" class="form-check-input" />
                <label asp-for="RememberMe" class="form-check-label"></label>
                <span asp-validation-for="RememberMe" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <button type="submit" class="btn btn-primary">Login</button>
                <a class="btn btn-secondary" asp-action="Login">Ir a Registro</a>
            </div>
            <div class="mb-3">
                <a class="btn btn-success" asp-action="ExternalLogin" asp-controller="Users" asp-route-provider="Microsoft">Continuar con microsoft</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

manageHomework/Views/Users/SignUp.cshtml
@model SignUpViewModel
@{
    ViewData["Title"] = "Registro";
}
<h1>Registrarse</h1>

<div class="card">
    <div class="card-body">
        <form asp-action="Signup">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="mb-3">
                <label asp-for="Email" class="form-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label asp-for="Password" class="form-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <button type="submit" class="btn btn-primary">Registrarse</button>
                <a class="btn btn-secondary" asp-action="Login">Ir a login</a>
            </div>
            <div class="mb-3">
                <a class="btn btn-success" asp-action="ExternalLogin" asp-controller="Users" asp-route-provider="Microsoft">Continuar con microsoft</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

manageHomework/Views/Users/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - manageHomework</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/manageHomework.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
</head>
<body style="margin:0;">
    <div style="display:flex; justify-content:center; align-items:center;height:100vh;">
        <div style="margin-right: 5rem;">
            <h1>Tares MVC</h1>
            <h4>esta aplicacion maneja las tareas.</h4>
        </div>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - manageHomework - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>